print("Program starting.")
firstWord = input("Insert first word: ")
secondWord = input("Insert second word: ")
print(f"1st word is {len(firstWord)} characters long.")
print(f"2nd word is {len(secondWord)} characters long.")
print(f"Words together makes one closed compound '{firstWord + secondWord}'.")
print("Program ending.") 